update=Fri 08 Jan 2016 02:01:48 PM EET
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=
PadDrill=1
PadDrillOvalY=1
PadSizeH=1.778
PadSizeV=1.778
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.254
ModuleOutlineThickness=0.15
[eeschema]
version=1
LibDir=../../../SVN/KiCAD_Components
[eeschema/libraries]
LibName1=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Antennas
LibName2=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Buttons
LibName3=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Connectors
LibName4=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Devices
LibName5=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Diodes
LibName6=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_IC
LibName7=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Jumpers
LibName8=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_OTHER
LibName9=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Power
LibName10=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_RCL
LibName11=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Regulators
LibName12=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Switches
LibName13=/home/bat_niki/Documents/SVN/KiCAD_Components/OLIMEX_Transistors
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
ERC_TestSimilarLabels=1
